extends: stylelint-config-standard
rules:
  indentation: 2

  declaration-block-single-line-max-declarations: 2

  max-empty-lines: 2
  selector-max-empty-lines: 2

  declaration-empty-line-before:
    - never
    - ignore:
      - after-declaration

  rule-empty-line-before: null

  block-opening-brace-space-before: null

  selector-list-comma-newline-after: null

  selector-type-no-unknown:
    - true
    - ignoreTypes:
      - menuseparator
      - dropmarker
